version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: peptok-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: peptok_dev
      POSTGRES_USER: peptok_user
      POSTGRES_PASSWORD: peptok_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-nestjs/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peptok_user -d peptok_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: peptok-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: peptok-network
